services:
  - type: web
    name: beast-studio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    envVars:
      - key: PORT
        value: 5000
